<?php

namespace AppBundle\Repository;

/**
 * JoursFeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoursFeriesRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * liste des jours feries actives
     * @return array
     */
    public function getListJoursFeries()
    {
        $zSql = "SELECT DATE(`jours_feries_date`) FROM `jours_feries` WHERE enabled=1";
        $qb = $this->getEntityManager()->getConnection()->prepare($zSql);
        $qb->execute();
        $result = $qb->fetchAll(\PDO::FETCH_COLUMN);


        return $result;
    }

}
