<?php

namespace AppBundle\Repository;

/**
 * ModeleWorkflowStepsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleWorkflowStepsRepository extends \Doctrine\ORM\EntityRepository
{
}
