<?php

namespace AppBundle\Repository;

/**
 * ModeleWorkflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleWorkflowRepository extends \Doctrine\ORM\EntityRepository
{
}
