<?php

namespace AppBundle\Repository;

/**
 * ModeleWorkflowStepsValidatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleWorkflowStepsValidatorRepository extends \Doctrine\ORM\EntityRepository
{

}
