<?php

namespace AppBundle\Repository;

/**
 * SocietyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocietyRepository extends \Doctrine\ORM\EntityRepository
{
}
