<?php

namespace AppBundle\Repository;

/**
 * TypeCongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCongeRepository extends \Doctrine\ORM\EntityRepository
{
}
